repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        exclude: .+\.(cns|cnr|tsv|csv|txt)$
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--unsafe]
      - id: check-added-large-files
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        args: [--line-length=130]
  - repo: https://github.com/snakemake/snakefmt
    rev: v0.8.4
    hooks:
      - id: snakefmt
        args: [--line-length=130]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        types_or: [css, html, javascript, yaml, json]
