files:
  - name: file_table
    type: file_table
    description: Comma or tab separated file
    input: config/file_table.csv
    nav_header: File types
  - name: plain_text
    type: plain_text
    description: plain text file
    input: config/plain_text.txt
    nav_header: File types
  - name: file_table (txt Tab-separated)
    type: file_table
    description: A tab separated txt file
    input: config/table.txt
    nav_header: File types
  - name: table
    type: table
    input: config/table.json
    description: Json file with json representation of a table
    nav_header: File types
  - name: file_link
    type: file_link
    input: results/cnv/{sample}_{type}.pathology.cnv_report.html
    description: File link to other results
    nav_header: File types
  - name: image
    type: image
    input: config/image.png
    description: Image file
    nav_header: File types
  - name: MultiQC
    type: multiqc
    input: config/multiqc_data.json
    sections: ["table"]
    description: multiqc general stats for this sample
    nav_header: File types
  - name: Empty file_table
    type: file_table
    description: A completely empty file with no headers
    input: config/empty_table2.tsv
    nav_header: File types
