---
output: "config/output_files.yaml"
resources: "config/resources.yaml"
samples: "samples.tsv"
units: "units.tsv"

default_container: "docker://hydragenetics/common:0.3.0"

reference:
  skip_chrs:
    - chrM

cnv_html_report:
  cytobands: false
  show_table: true

general_html_report:
  json: "reports/general_html_report/{sample}_{type}.general_report.json"

merge_cnv_json:
  annotations:
  cytobands:
  germline_vcf:
  filtered_cnv_vcfs:
  unfiltered_cnv_vcfs:
