---
output: "config/output_files.json"
resources: "config/resources.yaml"
samples: "samples.tsv"
units: "units.tsv"

default_container: "docker://hydragenetics/common:0.3.0"

reference:
  skip_chrs:
    - chrM

cnv_html_report:
  cytobands: false
  show_table: true

merge_cnv_json:
  annotations:
  cytobands:
  germline_vcf:
  filtered_cnv_vcfs:
  unfiltered_cnv_vcfs:
