amplification:
  all_of:
    - {field: adjusted_cn, operator: ">=", value: 6}
duplication:
  filter: false
  all_of:
    - {field: adjusted_cn, operator: ">", value: 2.5}
    - {field: adjusted_cn, operator: "<", value: 6}
deletion:
  all_of:
    - {field: adjusted_cn, operator: "<=", value: 1.4}
