$schema: "http://json-schema.org/draft-04/schema#"
description: snakemake configuration file
type: object
properties:
  samples:
    type: string
  units:
    type: string
  output:
    type: string
    description: output yaml/json file defining expected output from pipeline
  resources:
    type: string
    description: Path to resources.yaml file
  default_container:
    type: string
    description: name or path to a default docker/singularity container

  reference:
    type: object
    properties:
      fai:
        type: string
        format: uri-reference
    required:
      - fai

  cnv_html_report:
    type: object
    description: parameters for cnv_html_report
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded
      template_dir:
        type: string
        format: uri-reference
        description: >
          Path to the directory containing the template files for the CNV
          HTML report. The only required file in this directory is `index.html`
          which should be a jinja2 template for the report. Any JS (`*.js`) or
          CSS files (`*.css`) will be integrated into the report. These files
          are included according to the lexicographical order of the file names,
          so if order is important, name the files accordingly, e.g.
          `01-script.js`, `02-script.js`, etc.
      annotations:
        type: array
        description: >
          List of BED files with custom annotations.
        items:
          type: string
          format: uri-reference
          description: >
            BED file with annotations that should be added to the chromosome
            view of the report. Required columns are `chrom`, `chromStart`,
            `chromEnd` and `name`.
    required:
      - template_dir

  cnv_json:
    type: object
    description: parameters for cnv_json
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded

  merge_cnv_json:
    type: object
    description: parameters for merge_cnv_json
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded

required:
  - samples
  - units
  - output
  - resources
  - default_container

