resources: "resources.yaml"
samples: "samples.tsv"
units: "units.tsv"

output: output_files.yaml

default_container: "docker://hydragenetics/common:0.3.0"

reference:
  fai: reference/ref.fai
  skip_chrs:
    - chrM

cnv_html_report:
  cytobands: true
  show_table: true
  template_dir: ../../config/cnv_report_template

merge_cnv_json:
  annotations:
    - config/amp_genes.bed
    - config/loh_genes.bed
    - config/centromeres.bed
  cytobands: config/cytobands.txt
  filtered_cnv_vcfs:
    - cnv_sv/svdb_query/{sample}_{type}.{tc_method}.svdb_query.annotate_cnv.cnv_amp_genes.filter.cnv_hard_filter_amp.vcf
  germline_vcf: snv_indels/bcbio_variation_recall_ensemble/{sample}_{type}.ensembled.vep_annotated.filter.germline.exclude.blacklist.vcf
  unfiltered_cnv_vcfs:
    - cnv_sv/svdb_query/{sample}_{type}.{tc_method}.svdb_query.annotate_cnv.cnv_amp_genes.vcf

svdb_merge:
  tc_method:
    - name: pathology
      cnv_caller:
        - cnvkit
        - gatk
