output: "../../config/output_files.yaml"
resources: "resources.yaml"
samples: "samples.tsv"
units: "units.tsv"
default_container: "docker://hydragenetics/common:0.3.0"
general_report: "config/reports/general_report.yaml"

reference:
  fai: reference/ref.fai
  fasta: "reference/hg19.with.mt.fasta"

cnv_html_report:
  cytobands: true
  show_table: true
  extra_tables:
    - path: config/extra_table1.tsv
      name: Extra table
      description: An extra table with some extra information.
    - path: config/extra_table2.tsv
      name: Another extra table
      description: Another extra table with some extra extra information.
    - path: cnv_sv/svdb_query/{sample}_{type}.extra_table.tsv
      name: Extra table with wildcards
      description: >
        The file on which this table is based on has wildcards in
        the filename.
    - path: config/empty_table.tsv
      name: An empty table
      description: >
        A table that only has a header row, but no data. It should still
        be presented, but it should at the same time be clear that it is
        empty, and meant to be so.

general_html_report:
  final_directory_depth: 3
  multiqc_config: "config/reports/multiqc_config_dna.yaml"

merge_cnv_json:
  annotations:
    - config/amp_genes.bed
    - config/loh_genes.bed
    - config/centromeres.bed
  cytobands: config/cytobands.txt
  filtered_cnv_vcfs:
    - cnv_sv/svdb_query/{sample}_{type}.{tc_method}.svdb_query.annotate_cnv.cnv_amp_genes.filter.cnv_hard_filter_amp.vcf
    - cnv_sv/svdb_query/{sample}_{type}.{tc_method}.svdb_query.annotate_cnv.cnv_loh_genes.filter.cnv_hard_filter_loh.vcf
  germline_vcf: snv_indels/bcbio_variation_recall_ensemble/{sample}_{type}.ensembled.vep_annotated.filter.germline.exclude.blacklist.vcf
  unfiltered_cnv_vcfs:
    - cnv_sv/svdb_query/{sample}_{type}.{tc_method}.svdb_query.annotate_cnv.cnv_amp_genes.vcf
    - cnv_sv/svdb_query/{sample}_{type}.{tc_method}.svdb_query.annotate_cnv.cnv_loh_genes.vcf

svdb_merge:
  tc_method:
    - name: pathology
      cnv_caller:
        - cnvkit
        - gatk
        - jumble
