name: release-please
on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v3
        id: release
        with:
          release-type: simple
          package-name: reports
          default-branch: main
          extra-files: |
            workflow/templates/cnv_html_report/index.html
