name: Snakemake dry run

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main and develop branch
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  snakemake-dry-run:
    name: snakemake dry run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: 3.11
      - name: Install requirements.txt
        run: |
          pip install -r requirements.txt
      - name: Install requirements.test.txt
        run: |
          pip install -r requirements.test.txt
      - name: snakemake dry run
        working-directory: .tests/integration
        run: |
          snakemake -n -s ../../workflow/Snakefile --configfiles ../../config/config.yaml config.yaml
  snakemake-module-dry-run:
    name: snakemake module dry run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: 3.11
      - name: Install requirements.txt
        run: |
          pip install -r requirements.txt
      - name: Install requirements.test.txt
        run: |
          pip install -r requirements.test.txt
      - name: snakemake dry run
        working-directory: .tests/integration
        run: |
          snakemake -n -s Snakefile_module --configfiles ../../config/config.yaml config.yaml
